---
permalink: sm-storage/change-configuration-settings-for-a-pool.html 
sidebar: sidebar 
keywords: change, configuration, set, pool 
summary: 풀 이름을 변경하거나 용량 알림 설정, 수정 우선 순위 또는 보존 용량을 편집하려면 풀 설정을 편집할 수 있습니다. 
---
= 풀의 구성 설정을 변경합니다
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
풀 이름을 변경하거나 용량 알림 설정, 수정 우선 순위 또는 보존 용량을 편집하려면 풀 설정을 편집할 수 있습니다.

.단계
. 메뉴 * 선택: 스토리지 [풀 및 볼륨 그룹] *.
. 편집할 풀을 선택한 다음 * 설정 보기/편집 * 을 클릭합니다.
+
풀 설정 * 대화 상자가 나타납니다.

. Settings * 탭을 선택한 다음 필요에 따라 풀 설정을 편집합니다.
+
.필드 세부 정보
====
[cols="2*"]
|===
| 설정 | 설명 


 a| 
이름
 a| 
사용자 제공 풀 이름을 변경할 수 있습니다. 풀 이름을 지정해야 합니다.



 a| 
용량 알림
 a| 
풀의 사용 가능한 용량이 지정된 임계값에 도달하거나 이를 초과할 경우 알림 알림을 보낼 수 있습니다. 풀에 저장된 데이터가 지정된 임계값을 초과하면 System Manager에서 메시지를 보내 스토리지 공간을 추가하거나 불필요한 개체를 삭제할 시간을 지정합니다.

경고는 대시보드의 알림 영역에 표시되며 서버에서 이메일 및 SNMP 트랩 메시지를 통해 관리자에게 보낼 수 있습니다.

다음과 같은 용량 알림을 정의할 수 있습니다.

** * Critical alert * -- 풀의 사용 가능한 용량이 지정된 임계값에 도달하거나 이를 초과할 때 이 중요 알림을 보냅니다. 스피너 컨트롤을 사용하여 임계값 비율을 조정합니다. 이 알림을 비활성화하려면 확인란을 선택합니다.
** * Early alert * -- 풀의 사용 가능한 용량이 지정된 임계값에 도달하면 이 조기 알림이 표시됩니다. 스피너 컨트롤을 사용하여 임계값 비율을 조정합니다. 이 알림을 비활성화하려면 확인란을 선택합니다.




 a| 
수정 우선 순위
 a| 
시스템 성능과 관련하여 풀의 수정 작업에 대한 우선 순위 수준을 지정할 수 있습니다. 풀에서 수정 작업의 우선 순위가 높을수록 작업이 더 빨리 완료되지만 호스트 입출력 성능이 저하될 수 있습니다. 우선 순위가 낮으면 작업에 더 오래 걸리지만 호스트 I/O 성능에는 영향을 덜 받습니다.

최저, 최저, 중간, 높음, 최고 등 5가지 우선 순위 수준 중에서 선택할 수 있습니다. 우선 순위 수준이 높을수록 호스트 I/O 및 시스템 성능에 미치는 영향이 커집니다.

** * Critical reconstruction priority * -- 이 슬라이더 막대는 여러 드라이브에 장애가 발생하여 일부 데이터에 중복성이 없고 추가적인 드라이브 장애로 인해 데이터가 손실될 경우 데이터 재구성 작업의 우선순위를 결정합니다.
** * 저하된 재구성 우선순위 * -- 이 슬라이더 막대는 드라이브 장애가 발생했을 때 데이터 재구성 작업의 우선순위를 결정하지만, 데이터에는 중복성이 있으며 추가적인 드라이브 장애로 인해 데이터가 손실되지 않습니다.
** * 백그라운드 작업 우선 순위 * -- 이 슬라이더 막대는 풀이 최적 상태인 동안 발생하는 풀 백그라운드 작업의 우선 순위를 결정합니다. 이러한 작업에는 DVE(Dynamic Volume Expansion), iaf(Instant Availability Format) 및 교체되거나 추가된 드라이브로 데이터 마이그레이션 등이 있습니다.




 a| 
보존 용량
 a| 
드라이브 수를 정의하여 잠재적 드라이브 장애를 지원하기 위해 풀에 예약된 용량을 결정할 수 있습니다. 드라이브 장애가 발생하면 보존 용량이 재구성 데이터를 저장하는 데 사용됩니다. 풀은 볼륨 그룹에서 사용되는 핫 스페어 드라이브 대신 데이터 재구성 프로세스 중에 보존 용량을 사용합니다.

Spinner 컨트롤을 사용하여 드라이브 수를 조정합니다. 드라이브 수에 따라 풀의 보존 용량이 spinner 상자 옆에 표시됩니다.

보존 용량에 대한 다음 정보를 염두에 두십시오.

** 보존 용량은 풀의 총 가용 용량에서 차감되기 때문에 예비 용량을 예약하는 경우 볼륨을 생성하는 데 사용할 수 있는 가용 용량에 영향을 줍니다. 보존 용량에 0을 지정하면 풀의 모든 가용 용량이 볼륨 생성에 사용됩니다.
** 보존 용량을 줄이면 풀 볼륨에 사용할 수 있는 용량이 증가합니다.


|===
====
. 저장 * 을 클릭합니다.

