---
permalink: sm-storage/change-configuration-settings-for-a-volume-group.html 
sidebar: sidebar 
keywords: change, raid level, volume group 
summary: 볼륨 그룹에 액세스하는 응용 프로그램의 성능 요구 사항을 수용하기 위해 볼륨 그룹의 RAID 레벨을 변경할 수 있습니다. 이 작업은 데이터 입출력에 영향을 주지 않고 볼륨 그룹의 RAID 레벨을 변경합니다 
---
= 볼륨 그룹의 RAID 레벨을 변경합니다
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
볼륨 그룹에 액세스하는 응용 프로그램의 성능 요구 사항을 수용하기 위해 볼륨 그룹의 RAID 레벨을 변경할 수 있습니다. 이 작업은 데이터 입출력에 영향을 주지 않고 볼륨 그룹의 RAID 레벨을 변경합니다

.시작하기 전에
* 볼륨 그룹이 Optimal(최적) 상태여야 합니다.
* 새 RAID 레벨로 변환하려면 볼륨 그룹에 충분한 용량이 있어야 합니다.
* 풀의 RAID 레벨은 변경할 수 없습니다. System Manager는 풀을 RAID 6으로 자동 구성합니다.


.이 작업에 대해
이 작업을 시작한 후에는 취소할 수 없습니다. 이 작업 중에도 데이터를 계속 사용할 수 있습니다.

RAID 레벨에 대해 자세히 알아보십시오

[cols="2*"]
|===
| RAID 레벨 | 설명 


 a| 
RAID 0 스트라이핑
 a| 
고성능을 제공하지만 데이터 중복성을 제공하지 않습니다. 볼륨 그룹에서 단일 드라이브에 장애가 발생하면 연결된 모든 볼륨이 실패하고 모든 데이터가 손실됩니다.

스트라이핑 RAID 그룹은 두 개 이상의 드라이브를 하나의 대용량 논리 드라이브로 결합합니다.



 a| 
RAID 1 미러링
 a| 
고성능 및 최고의 데이터 가용성을 제공하며 기업 또는 개인 차원에서 중요한 데이터를 저장하는 데 적합합니다.

한 드라이브의 내용을 미러링된 쌍의 두 번째 드라이브에 자동으로 미러링하여 데이터를 보호합니다. 단일 드라이브 장애 시 보호 기능을 제공합니다.



 a| 
RAID 10 스트라이핑/미러링
 a| 
RAID 0(스트라이핑)과 RAID 1(미러링)의 조합을 제공하며, 4개 이상의 드라이브를 선택할 때 가능합니다.

RAID 10은 고성능 및 내결함성이 필요한 데이터베이스와 같은 대용량 트랜잭션 애플리케이션에 적합합니다.



 a| 
RAID 5
 a| 
일반적인 I/O 크기가 작고 읽기 작업이 많은 다중 사용자 환경(예: 데이터베이스 또는 파일 시스템 스토리지)에 적합합니다.



 a| 
RAID 6
 a| 
RAID 5 이상의 이중화 보호가 필요하지만 높은 쓰기 성능이 필요하지 않은 환경에 적합합니다.

|===
RAID 3은 CLI(Command Line Interface)를 사용하여 볼륨 그룹에만 할당할 수 있습니다.

.단계
. 메뉴 * 선택: 스토리지 [풀 및 볼륨 그룹] *.
. 편집할 볼륨 그룹을 선택한 다음 * 설정 보기/편집 * 을 클릭합니다.
+
볼륨 그룹 설정 대화 상자가 나타납니다.

. 드롭다운 목록에서 RAID 레벨을 선택한 다음 * 저장 * 을 클릭합니다.
+
RAID 레벨 변경으로 인해 용량이 줄어들거나, 볼륨 중복성이 손실되거나, 쉘프/드로어 손실 보호가 손실되면 확인 대화 상자가 나타납니다. 계속하려면 * 예 * 를 선택하고, 그렇지 않으면 * 아니요 * 를 클릭합니다.



.결과
볼륨 그룹의 RAID 레벨을 변경하면 System Manager가 볼륨 그룹을 구성하는 모든 볼륨의 RAID 레벨을 변경합니다. 작업 중에 성능이 약간 영향을 받을 수 있습니다.
