---
permalink: sm-storage/create-asynchronous-mirrored-volume.html 
sidebar: sidebar 
keywords: create, asynchronous, mirrored, volume 
summary: 볼륨을 비동기적으로 미러링하여 원격 스토리지 시스템의 데이터를 로컬 스토리지 시스템의 일관된 시점 데이터 복제본으로 유지합니다. 이렇게 하려면 미러 정합성 보장 그룹을 생성하여 두 스토리지 시스템 간의 미러링 관계를 설정한 다음 미러에서 사용할 운영 볼륨과 2차 볼륨을 선택합니다. 
---
= 비동기식 미러링된 볼륨 생성
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
볼륨을 비동기적으로 미러링하여 원격 스토리지 시스템의 데이터를 로컬 스토리지 시스템의 일관된 시점 데이터 복제본으로 유지합니다. 이렇게 하려면 미러 정합성 보장 그룹을 생성하여 두 스토리지 시스템 간의 미러링 관계를 설정한 다음 미러에서 사용할 운영 볼륨과 2차 볼륨을 선택합니다.

.시작하기 전에
* 다음 조건을 설정해야 합니다.
+
** 웹 서비스 프록시 서비스가 실행 중입니다.
** SANtricity Unified Manager가 HTTPS 연결을 통해 로컬 호스트에서 실행되고 있습니다.
** 기본 어레이와 보조 어레이의 각 컨트롤러에는 이더넷 관리 포트가 구성되어 있어야 하며 네트워크에 연결되어 있어야 합니다.
** SANtricity Unified Manager에 스토리지 시스템에 대한 유효한 SSL 인증서가 표시됩니다. 자체 서명된 인증서를 수락하거나 Unified Manager를 사용하여 인증서 [인증서 관리] 메뉴로 이동하여 자체 보안 인증서를 설치할 수 있습니다.
** SANtricity System Manager는 Unified Manager에서 실행됩니다.
** 데이터를 미러링할 두 스토리지 시스템이 검색되어야 합니다. 그런 다음 Unified Manager에서 운영 볼륨의 스토리지 어레이를 선택하고 * Launch * 를 클릭하여 브라우저 기반 SANtricity System Manager를 엽니다.


* 로컬 및 원격 스토리지 배열의 암호를 알아야 합니다.
* 로컬 및 원격 스토리지 시스템은 Fibre Channel 패브릭 또는 iSCSI 인터페이스를 통해 접속되어야 합니다.


.이 작업에 대해
볼륨을 비동기적으로 미러링하는 프로세스는 다음과 같은 여러 단계로 이루어집니다.

* <<1단계: 미러 정합성 보장 그룹을 생성하거나 기존 정합성 보장 그룹을 선택합니다>>
* <<2단계: 운영 볼륨을 선택합니다>>
* <<3단계: 보조 볼륨을 선택합니다>>


볼륨은 하나의 미러 관계에만 참여할 수 있습니다.



== 1단계: 미러 정합성 보장 그룹을 생성하거나 기존 정합성 보장 그룹을 선택합니다

[role="lead"]
미러 정합성 보장 그룹을 생성하거나 기존 정합성 보장 그룹을 선택하여 로컬 스토리지 시스템과 원격 스토리지 시스템 간의 미러링 관계를 설정합니다.

.이 작업에 대해
생성할 수 있는 미러 정합성 보장 그룹 관계와 미러링된 쌍 관계의 수는 스토리지 어레이의 하드웨어에 따라 다릅니다.

.단계
. 다음 작업 중 하나를 수행하여 비동기식 미러링 시퀀스에 액세스합니다.
+
** 메뉴: 스토리지 [비동기 미러링 > 미러링된 쌍 생성]을 선택합니다.
** 메뉴: 스토리지 [볼륨 > 복제 서비스 > 볼륨 비동기적으로 미러]를 선택합니다.


. 기존 미러 일관성 그룹을 선택하거나 새 미러 일관성 그룹을 생성합니다.
+
새 미러 정합성 보장 그룹을 생성하려면 다음을 수행합니다.

+
.. 두 스토리지 어레이 간에 미러링될 볼륨의 데이터를 가장 잘 설명하는 고유한 이름을 입력합니다(예: R&D 데이터).
.. 로컬 스토리지 시스템과 미러 관계를 설정할 원격 스토리지 시스템을 선택합니다.
+
[NOTE]
====
원격 스토리지 배열이 암호로 보호되어 있는 경우 암호를 입력하라는 메시지가 표시됩니다.

====
.. 원격 스토리지 시스템에서 미러링된 쌍을 수동 또는 자동으로 재동기화할지 여부를 선택합니다.
+
*** * 수동 * -- 수동 재동기화 메뉴 옵션을 사용하여 2차 시점 이미지를 명시적으로 업데이트해야 합니다. 비동기식 미러 그룹 내의 모든 비동기식 미러링된 페어에 대해 재동기화를 수동으로 시작하려면 이 옵션을 선택합니다.
*** * 자동 * -- 드롭다운을 사용하여 이전 업데이트 시작에서 다음 업데이트 시작까지의 시간을 지정합니다. 자동 동기화 간격을 기본값인 10분마다 변경하려면 분 단위로 정의된 간격 값을 편집합니다.


.. Create * 를 클릭합니다.
+
System Manager는 먼저 로컬 스토리지 시스템에 미러 정합성 보장 그룹을 생성한 다음 원격 스토리지 시스템에 미러 정합성 보장 그룹을 생성합니다.

+
[NOTE]
====
System Manager가 로컬 스토리지 시스템에 미러 정합성 보장 그룹을 생성했지만 원격 스토리지 시스템에 생성하지 못한 경우 로컬 스토리지 시스템에서 미러 정합성 보장 그룹을 자동으로 삭제합니다. System Manager에서 미러 정합성 보장 그룹을 삭제하려는 동안 오류가 발생하면 수동으로 삭제해야 합니다.

====


. Next * 를 선택하고 로 이동합니다 <<2단계: 운영 볼륨을 선택합니다>>.




== 2단계: 운영 볼륨을 선택합니다

[role="lead"]
미러 관계에 사용할 운영 볼륨을 선택하고 예약된 용량을 할당해야 합니다. 로컬 스토리지 시스템의 미러 정합성 보장 그룹에 추가된 볼륨은 미러 관계에서 1차 역할을 유지합니다.

.단계
. 미러의 운영 볼륨으로 사용할 기존 볼륨을 선택한 후 * 다음 * 을 클릭하여 예약된 용량을 할당합니다.
. 선택한 운영 볼륨에 예약된 용량을 할당합니다. 다음 작업 중 하나를 수행합니다.
+
** * 기본 설정 수락 * -- 이 권장 옵션을 사용하여 기본 볼륨에 예약된 용량을 기본 설정으로 할당합니다.
** * 비동기식 미러링과 관련된 데이터 스토리지 요구 사항을 충족하기 위해 예약된 용량 설정을 할당합니다. * -- 다음 지침에 따라 예약된 용량을 할당합니다.
+
*** 예약된 용량의 기본 설정은 기본 볼륨 용량의 20%이며 일반적으로 이 용량이면 충분합니다.
*** 필요한 용량은 운영 볼륨에 대한 I/O 쓰기의 빈도 및 크기와 용량을 유지하는 데 필요한 기간에 따라 달라집니다.
*** 일반적으로 다음 조건 중 하나 또는 둘 다 존재할 경우 예약된 용량에 더 큰 용량을 선택합니다.
+
**** 미러링 쌍을 장기간 유지하려고 합니다.
**** 입출력 작업이 많은 경우 운영 볼륨에서 데이터 블록의 비율이 크게 변경됩니다. 기간별 성능 데이터 또는 기타 운영 체제 유틸리티를 사용하여 기본 볼륨에 대한 일반적인 I/O 작업을 결정할 수 있습니다.






. Next * 를 선택하고 로 이동합니다 <<3단계: 보조 볼륨을 선택합니다>>.




== 3단계: 보조 볼륨을 선택합니다

[role="lead"]
미러 관계에 사용할 2차 볼륨을 선택하고 예약된 용량을 할당해야 합니다. 원격 스토리지 시스템의 미러 정합성 보장 그룹에 추가된 볼륨은 미러 관계에서 2차 역할을 유지합니다.

.이 작업에 대해
원격 스토리지 어레이에서 보조 볼륨을 선택하면 해당 미러링된 쌍에 대해 적합한 모든 볼륨 목록이 표시됩니다. 사용할 수 없는 볼륨은 해당 목록에 표시되지 않습니다.

.단계
. 미러링된 쌍의 보조 볼륨으로 사용할 기존 볼륨을 선택한 후 * Next * 를 클릭하여 예약된 용량을 할당합니다.
. 선택한 보조 볼륨에 예약된 용량을 할당합니다. 다음 작업 중 하나를 수행합니다.
+
** * 기본 설정 수락 * -- 이 권장 옵션을 사용하여 보조 볼륨에 예약된 용량을 기본 설정으로 할당합니다.
** * 비동기식 미러링과 관련된 데이터 스토리지 요구 사항을 충족하기 위해 예약된 용량 설정을 할당합니다. * -- 다음 지침에 따라 예약된 용량을 할당합니다.
+
*** 예약된 용량의 기본 설정은 기본 볼륨 용량의 20%이며 일반적으로 이 용량이면 충분합니다.
*** 필요한 용량은 운영 볼륨에 대한 I/O 쓰기의 빈도 및 크기와 용량을 유지하는 데 필요한 기간에 따라 달라집니다.
*** 일반적으로 다음 조건 중 하나 또는 둘 다 존재할 경우 예약된 용량에 더 큰 용량을 선택합니다.
+
**** 미러링 쌍을 장기간 유지하려고 합니다.
**** 입출력 작업이 많은 경우 운영 볼륨에서 데이터 블록의 비율이 크게 변경됩니다. 기간별 성능 데이터 또는 기타 운영 체제 유틸리티를 사용하여 기본 볼륨에 대한 일반적인 I/O 작업을 결정할 수 있습니다.






. 비동기 미러링 시퀀스를 완료하려면 * Finish * 를 선택합니다.


.결과
System Manager는 다음 작업을 수행합니다.

* 로컬 스토리지와 원격 스토리지 시스템 간의 초기 동기화를 시작합니다.
* 미러링되는 볼륨이 씬 볼륨인 경우 초기 동기화 중에 프로비저닝된 블록(보고된 용량이 아닌 할당된 용량)만 보조 볼륨으로 전송됩니다. 이렇게 하면 초기 동기화를 완료하기 위해 전송해야 하는 데이터의 양이 줄어듭니다.
* 로컬 스토리지 시스템 및 원격 스토리지 시스템에서 미러링된 쌍에 대한 예약된 용량을 생성합니다.

