---
permalink: sm-mirroring/considerations-for-setting-up-asynchronous-mirroring.html 
sidebar: sidebar 
keywords: considerations, setting up, asynchronous, mirror 
summary: 성공적인 구성과 설정을 위해 계획의 일환으로 몇 가지 주요 고려 사항을 염두에 두십시오. 
---
= 비동기 미러링 설정을 위한 고려 사항
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
성공적인 구성과 설정을 위해 계획의 일환으로 몇 가지 주요 고려 사항을 염두에 두십시오.



== SANtricity Unified Manager를 실행합니다

* 기본 어레이와 보조 어레이의 각 컨트롤러에는 이더넷 관리 포트가 구성되어 있어야 하며 네트워크에 연결되어 있어야 합니다.
* 비동기식 미러링은 SANtricity Unified Manager를 열어서 구성합니다. 모든 미러링 관계의 경우 로컬 및 원격 스토리지 시스템이 SANtricity Unified Manager에서 검색되고 목록에 있어야 합니다.
* 브라우저 기반 SANtricity Unified Manager가 설치되어 있고 데이터를 미러링할 두 스토리지 어레이가 검색되어 있어야 합니다. 그런 다음 Unified Manager에서 운영 볼륨의 스토리지 어레이를 선택하고 Launch를 클릭하여 브라우저 기반 SANtricity System Manager를 엽니다.




== 활성화 중

비동기식 미러링을 사용하기 전에 미러링 작업에 참여하는 각 스토리지 어레이에서 활성화해야 합니다. 활성화는 CLI, REST API 또는 관리 그래픽 사용자 인터페이스(GUI)를 통해 수행할 수 있습니다.

* SANtricity System Manager(E2800, E5700, EF570)에서 관리되는 시스템의 경우 별도의 활성화 단계가 필요하지 않습니다. 미러 그룹/쌍이 설정되는 동안 뒤에서 활성화가 수행됩니다.
* SANtricity 스토리지 관리자(E2700, E5600, EF560)에서 관리하는 시스템의 경우, SANtricity 시스템 관리자가 관리하지 않는 기존 시스템의 GUI를 사용하여 비동기식 미러링을 활성화합니다. 비동기식 미러링에 iSCSI를 사용하는 경우에는 활성화 단계가 필요하지 않습니다.




== 웹 서비스 인증서 및 권장 브라우저

* * 신뢰할 수 있는 인증서 *
+
SANtricity System Manager에서 관리하는 시스템을 포함하는 미러링의 경우 스토리지 시스템이 웹 서버에서 인증할 수 있도록 SANtricity Unified Manager에서 웹 서비스에 대한 신뢰할 수 있는 인증서를 가져오는 것이 좋습니다. SANtricity Unified Manager의 단계는 다음과 같습니다.

+
.. SANtricity Unified Manager가 설치된 시스템에 대한 CSR(인증서 서명 요청)을 생성합니다.
.. CSR을 인증 기관(CA)에 보냅니다.
.. CA에서 서명된 인증서를 다시 보내면 Unified Manager에서 가져옵니다.


* * 자체 서명된 인증서 *
+
자체 서명된 인증서도 사용할 수 있습니다. 관리자가 서명된 인증서를 가져오지 않고 미러링을 구성하려고 하면 SANtricity 시스템 관리자가 자체 서명된 인증서를 수락할 수 있는 오류 대화 상자가 표시됩니다. 이 경우 브라우저에서 Chrome 또는 Firefox의 최신 버전을 사용하는 것이 좋습니다.

+
자체 서명된 인증서를 수락하거나 Unified Manager를 사용하여 인증서 [인증서 관리] 메뉴로 이동하여 자체 보안 인증서를 설치할 수 있습니다.





== 지원되는 연결입니다

비동기 미러링은 FC 또는 iSCSI 연결을 사용하거나 둘 다 로컬 및 원격 스토리지 시스템 간의 통신에 사용할 수 있습니다. 미러 정합성 보장 그룹(비동기식 미러 그룹이라고도 함)을 생성할 때 관리자는 둘 다 원격 스토리지 시스템에 접속된 경우 해당 그룹에 대해 FC 또는 iSCSI를 선택할 수 있습니다. 한 채널 유형에서 다른 채널 유형으로 대체 작동이 없습니다.

비동기식 미러링은 스토리지 시스템의 호스트 측 I/O 포트를 사용하여 미러링된 데이터를 운영 측에서 2차 측으로 전달합니다.

* * 파이버 채널(FC) 인터페이스를 통한 미러링 *
+
스토리지 어레이의 각 컨트롤러는 가장 높은 번호가 지정된 FC 호스트 포트를 미러링 작업에 사용합니다.

+
컨트롤러에 기본 FC 포트와 HIC(호스트 인터페이스 카드) FC 포트가 모두 있는 경우 가장 높은 번호가 지정된 포트가 HIC에 있습니다. 전용 포트에 로그온한 호스트는 로그아웃되며 호스트 로그인 요청은 허용되지 않습니다. 이 포트의 I/O 요청은 미러링 작업에 사용되는 컨트롤러에서만 허용됩니다.

+
전용 미러링 포트는 디렉토리 서비스 및 네임 서비스 인터페이스를 지원하는 FC 패브릭 환경에 연결해야 합니다. 특히 FC-AL 및 지점 간 연결 옵션은 미러 관계에 참여하는 컨트롤러 간의 연결 옵션으로 지원되지 않습니다.

* * iSCSI 인터페이스를 통한 미러링 *
+
FC와 달리 iSCSI에는 전용 포트가 필요하지 않습니다. iSCSI 환경에서 비동기 미러링을 사용하는 경우 비동기 미러링에 사용하기 위해 스토리지 어레이의 프런트 엔드 iSCSI 포트 중 하나를 전용으로 지정할 필요가 없습니다. 이러한 포트는 비동기 미러 트래픽과 호스트-스토리지 I/O 연결을 위해 모두 공유됩니다.

+
컨트롤러는 iSCSI 이니시에이터가 세션을 설정하려고 시도하는 원격 스토리지 시스템의 목록을 유지합니다. iSCSI 연결을 성공적으로 설정하는 첫 번째 포트는 해당 원격 스토리지 시스템과의 이후의 모든 통신에 사용됩니다. 통신이 실패하면 사용 가능한 모든 포트를 사용하여 새 세션이 시도됩니다.

+
iSCSI 포트는 포트별로 어레이 레벨에서 구성됩니다. 구성 메시징 및 데이터 전송을 위한 컨트롤러 간 통신은 다음 설정을 포함한 글로벌 설정을 사용합니다.

+
** VLAN: 로컬 시스템과 원격 시스템 모두 동일한 VLAN 설정을 사용하여 통신해야 합니다
** iSCSI 수신 포트입니다
** 점보 프레임
** 이더넷 우선 순위


+
[NOTE]
====
iSCSI 인터컨트롤러 통신은 관리 이더넷 포트가 아닌 호스트 연결 포트를 사용해야 합니다.

====


비동기식 미러링은 스토리지 시스템의 호스트 측 I/O 포트를 사용하여 미러링된 데이터를 운영 측에서 2차 측으로 전달합니다. 비동기 미러링은 대기 시간이 더 짧고 비용이 저렴한 네트워크에 사용하기 때문에 iSCSI(TCP/IP 기반) 연결이 적합합니다. iSCSI 환경에서 비동기 미러링을 사용하는 경우 비동기 미러링에 사용하기 위해 어레이의 프런트 엔드 iSCSI 포트 중 하나를 전용으로 지정할 필요가 없습니다. 이러한 포트는 비동기 미러 트래픽과 호스트-스토리지 I/O 연결을 위해 모두 공유됩니다
