---
permalink: sm-mirroring/create-synchronous-mirrored-volume.html 
sidebar: sidebar 
keywords: create, synchronous, mirrored, volume 
summary: 볼륨을 동기식으로 미러링하여 스토리지 어레이 간에 데이터를 실시간으로 복제하므로 시스템 및 사이트 장애로부터 정보가 보호됩니다. 로컬 스토리지와 원격 스토리지 시스템 간의 동기식 미러링 관계에 사용할 운영 볼륨과 보조 볼륨을 선택하여 이 작업을 수행합니다. 
---
= 동기식 미러링 볼륨을 생성합니다
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
볼륨을 동기식으로 미러링하여 스토리지 어레이 간에 데이터를 실시간으로 복제하므로 시스템 및 사이트 장애로부터 정보가 보호됩니다. 로컬 스토리지와 원격 스토리지 시스템 간의 동기식 미러링 관계에 사용할 운영 볼륨과 보조 볼륨을 선택하여 이 작업을 수행합니다.

.시작하기 전에
* 동기식 미러링 기능을 사용하려면 여러 스토리지 어레이를 관리해야 하므로 브라우저 기반 SANtricity Unified Manager가 설치되어 있어야 하며 데이터를 미러링할 두 스토리지 어레이가 검색되었습니다. 그런 다음 Unified Manager에서 운영 볼륨의 스토리지 어레이를 선택하고 Launch를 클릭하여 브라우저 기반 SANtricity System Manager를 엽니다.
* 두 개의 스토리지 어레이가 있어야 합니다.
* 각 스토리지 어레이에는 2개의 컨트롤러가 필요합니다.
* 운영 및 2차 볼륨의 스토리지 어레이에서 다양한 OS 버전을 실행할 수 있습니다. 지원되는 최소 버전은 7.84입니다.
* 로컬 및 원격 스토리지 배열의 암호를 알아야 합니다.
* 로컬 및 원격 스토리지 시스템은 Fibre Channel Fabric을 통해 접속되어야 합니다.
* 동기식 미러 관계에 사용할 운영 볼륨과 2차 볼륨을 모두 생성해야 합니다.


.이 작업에 대해
볼륨을 동기식으로 미러링하는 프로세스는 다단계 절차입니다.

* <<1단계: 운영 볼륨을 선택합니다>>
* <<2단계: 보조 볼륨을 선택합니다>>
* <<3단계: 동기화 설정을 선택합니다>>


볼륨은 하나의 미러 관계에만 참여할 수 있습니다.



== 1단계: 운영 볼륨을 선택합니다

[role="lead"]
동기식 미러 관계에 사용할 운영 볼륨을 선택해야 합니다. 이 볼륨은 미러 관계에서 1차 역할을 보유합니다.

.시작하기 전에
* 동기식 미러 관계에 사용할 운영 볼륨을 생성해야 합니다.
* 운영 볼륨은 표준 볼륨이어야 합니다. 씬 볼륨이거나 스냅샷 볼륨일 수 없습니다.


.단계
. 동기 미러링 시퀀스에 액세스하려면 다음 작업 중 하나를 수행합니다.
+
** 메뉴: 스토리지 [동기 미러링 > 미러 볼륨]을 선택합니다.
** 메뉴: 스토리지 [볼륨 > 복제 서비스 > 볼륨 동기식 미러링]을 선택합니다. 동기식 미러링 쌍 생성 * 대화 상자가 나타납니다.


. 미러의 운영 볼륨으로 사용할 기존 볼륨을 선택합니다.
+
[NOTE]
====
볼륨 타일에서 볼륨을 선택했고 미러링이 가능한 경우 기본적으로 선택됩니다.

====
. Next * 를 선택하고 로 이동합니다 <<2단계: 보조 볼륨을 선택합니다>>.




== 2단계: 보조 볼륨을 선택합니다

[role="lead"]
미러 관계에 사용할 보조 볼륨을 선택해야 합니다. 이 볼륨은 미러 관계에서 2차 역할을 유지합니다.

.시작하기 전에
* 동기식 미러 관계에서 사용할 보조 볼륨을 생성해야 합니다.
* 2차 볼륨은 표준 볼륨이어야 합니다. 씬 볼륨이거나 스냅샷 볼륨일 수 없습니다.
* 2차 볼륨의 크기는 운영 볼륨만큼 크지 않아야 합니다.


.이 작업에 대해
원격 스토리지 어레이에서 보조 볼륨을 선택하면 해당 미러링된 쌍에 대해 적합한 모든 볼륨 목록이 표시됩니다. 사용할 수 없는 볼륨은 해당 목록에 표시되지 않습니다.

이 대화 상자에 표시되는 볼륨은 용량별로 정렬되며, 운영 볼륨 용량에 가장 가까운 볼륨부터 시작합니다. 용량이 동일한 볼륨은 알파벳순으로 정렬됩니다.

.단계
. 로컬 스토리지 시스템과 미러 관계를 설정할 원격 스토리지 시스템을 선택합니다.
+
[NOTE]
====
원격 스토리지 배열이 암호로 보호되어 있는 경우 암호를 입력하라는 메시지가 표시됩니다.

====
+
** 스토리지 배열은 해당 스토리지 배열 이름으로 나열됩니다. 스토리지 배열의 이름을 지정하지 않은 경우 이름이 "UNNAMED(명명되지 않음)"으로 표시됩니다.
** 사용하려는 스토리지 배열이 목록에 없는 경우 SANtricity 스토리지 관리자의 EMW(엔터프라이즈 관리 창)를 사용하여 추가합니다. 메뉴 선택: Edit [Add Storage Array](스토리지 배열 추가)를 선택합니다.


. 미러의 2차 볼륨으로 사용할 기존 볼륨을 선택합니다.
+
[NOTE]
====
운영 볼륨보다 큰 용량으로 2차 볼륨을 선택하는 경우 사용 가능한 용량이 운영 볼륨의 크기로 제한됩니다.

====
. 다음 * 을 클릭하고 으로 이동합니다 <<3단계: 동기화 설정을 선택합니다>>.




== 3단계: 동기화 설정을 선택합니다

[role="lead"]
통신이 중단된 후 기본 볼륨의 컨트롤러 소유자가 데이터를 보조 볼륨과 재동기화하는 우선 순위를 설정해야 합니다. 수동 또는 자동 재동기화 정책도 선택해야 합니다.

.단계
. 슬라이더 막대를 사용하여 동기화 우선 순위를 설정합니다.
+
동기화 우선 순위는 서비스 입출력 요청과 비교하여 통신 중단 후 초기 동기화 및 재동기화 작업을 완료하는 데 사용되는 시스템 리소스의 양을 결정합니다.

+
이 대화 상자에 설정된 우선 순위는 운영 볼륨과 2차 볼륨 모두에 적용됩니다. 나중에 스토리지 [Synchronous Mirroring > More > Edit Settings] 메뉴를 선택하여 운영 볼륨의 속도를 수정할 수 있습니다.

+
.동기화 속도에 대해 자세히 알아보십시오
[%collapsible]
====
동기화 우선 순위는 5가지입니다.

** 최저
** 낮음
** 중간
** 높음
** 가장 높음 동기화 우선 순위가 가장 낮은 속도로 설정되면 입출력 작업이 우선 순위가 지정되고 재동기화 작업이 더 오래 걸립니다. 동기화 우선 순위가 가장 높은 속도로 설정된 경우 재동기화 작업의 우선 순위가 지정되지만 스토리지 시스템의 입출력 작업이 영향을 받을 수 있습니다.


====
. 원격 스토리지 시스템에서 미러링된 쌍을 수동 또는 자동으로 재동기화할지 여부를 선택합니다.
+
** * 수동 * (권장 옵션) -- 미러링된 쌍으로 통신이 복구된 후 수동으로 동기화를 재개하려면 이 옵션을 선택합니다. 이 옵션은 데이터를 복구할 수 있는 최적의 기회를 제공합니다.
** * 자동 * -- 통신이 미러링된 쌍으로 복구된 후 재동기화를 자동으로 시작하려면 이 옵션을 선택합니다. 동기화를 수동으로 재개하려면 메뉴: 저장소 [동기 미러링]으로 이동하여 테이블에서 미러링된 쌍을 강조 표시하고 자세히 아래에서 다시 시작을 선택합니다.


. 동기식 미러링 시퀀스를 완료하려면 * Finish * 를 클릭합니다.


.결과
System Manager는 다음 작업을 수행합니다.

* 동기 미러링 기능을 활성화합니다.
* 로컬 스토리지와 원격 스토리지 시스템 간의 초기 동기화를 시작합니다.
* 동기화 우선 순위 및 재동기화 정책을 설정합니다.


.작업을 마친 후
동기 미러링 작업의 진행률을 보려면 Home [View Operations in Progress] 메뉴를 선택합니다. 이 작업은 시간이 오래 걸릴 수 있으며 시스템 성능에 영향을 줄 수 있습니다.
