---
permalink: sm-mirroring/requirements-for-using-asynchronous-mirroring.html 
sidebar: sidebar 
keywords: requirements, use, asynchronous, mirroring 
summary: 비동기 미러링 기능을 사용하려는 경우 다음 요구 사항을 염두에 두십시오. 
---
= 비동기 미러링 사용에 대한 요구 사항
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
비동기 미러링 기능을 사용하려는 경우 다음 요구 사항을 염두에 두십시오.



== SANtricity 유니파이드 관리자

비동기 미러링을 사용하려면 다음 조건을 설정해야 합니다.

* 웹 서비스 프록시 서비스가 실행 중입니다.
* SANtricity Unified Manager가 HTTPS 연결을 통해 로컬 호스트에서 실행되고 있습니다.
* 기본 어레이와 보조 어레이의 각 컨트롤러에는 이더넷 관리 포트가 구성되어 있어야 하며 네트워크에 연결되어 있어야 합니다.
* SANtricity Unified Manager에 스토리지 시스템에 대한 유효한 SSL 인증서가 표시됩니다. 자체 서명된 인증서를 수락하거나 Unified Manager를 사용하여 인증서 [인증서 관리] 메뉴로 이동하여 자체 보안 인증서를 설치할 수 있습니다.
* SANtricity System Manager는 Unified Manager에서 실행됩니다.
* 데이터를 미러링할 두 스토리지 시스템이 검색되어야 합니다. 그런 다음 Unified Manager에서 운영 볼륨의 스토리지 어레이를 선택하고 * Launch * 를 클릭하여 브라우저 기반 SANtricity System Manager를 엽니다.




== 지원합니다

* 두 개의 스토리지 어레이가 있어야 합니다.
* 기본 어레이와 보조 어레이의 각 컨트롤러에는 이더넷 관리 포트가 구성되어 있어야 하며 네트워크에 연결되어 있어야 합니다.
* 각 스토리지 어레이에는 2개의 컨트롤러가 필요합니다.
* 운영 및 2차 볼륨의 스토리지 어레이에서 다양한 OS 버전을 실행할 수 있습니다. 지원되는 최소 버전은 7.84입니다.
* 로컬 및 원격 스토리지 배열의 암호를 알아야 합니다.
* 미러링할 운영 볼륨과 같거나 더 큰 보조 볼륨을 생성하려면 원격 스토리지 시스템에 사용 가능한 용량이 충분해야 합니다.
* 로컬 및 원격 스토리지 시스템은 Fibre Channel 패브릭 또는 iSCSI 인터페이스를 통해 접속되어야 합니다.




== 지원되는 하드웨어 구성 및 연결 요구 사항

* 비동기식 미러링은 이중 컨트롤러 하드웨어 구성에서만 지원됩니다.
* 비동기 미러링 기능에 대한 통신은 FC(Fibre Channel) 또는 iSCSI 호스트 포트가 있는 컨트롤러에서만 지원됩니다. 이 기능은 로컬 스토리지 어레이와 원격 스토리지 어레이에 있는 각 컨트롤러의 호스트 포트 중 하나를 사용합니다.
* 스토리지 시스템이 FC 연결 및 iSCSI 접속으로 모두 연결되어 있는 경우 하나의 비동기식 미러 그룹을 FC를 통해 미러링할 수 있고 다른 비동기식 미러 그룹은 iSCSI를 통해 미러링될 수 있습니다.




== 미러링 볼륨 후보

* RAID 레벨, 캐싱 매개 변수 및 세그먼트 크기는 비동기식 미러링 쌍의 운영 볼륨과 2차 볼륨에서 서로 다를 수 있습니다.
* 2차 볼륨의 크기는 운영 볼륨만큼 크지 않아야 합니다.
* 볼륨은 하나의 미러 관계에만 참여할 수 있습니다.




== 예약된 용량입니다

* 컨트롤러 재설정 및 기타 임시 중단으로부터 복구하기 위해 쓰기 정보를 로깅하기 위해 미러링된 쌍의 보조 볼륨과 운영 볼륨에 예약된 용량 볼륨이 필요합니다.
* 미러링 쌍의 운영 볼륨과 2차 볼륨 모두에 추가 예약 용량이 필요하므로 미러 관계의 두 스토리지 어레이에서 사용 가능한 용량이 있는지 확인해야 합니다.




== 드라이브 보안 기능

* 보안 가능 드라이브를 사용하는 경우 기본 볼륨 및 보조 볼륨에 호환되는 보안 설정이 있어야 합니다. 이 제한은 적용되지 않으므로 직접 확인해야 합니다.
* 보안 가능 드라이브를 사용하는 경우 기본 볼륨과 보조 볼륨은 동일한 드라이브 유형을 사용해야 합니다. 이 제한은 적용되지 않으므로 직접 확인해야 합니다.
* DA(Data Assurance)를 사용하는 경우 운영 볼륨과 보조 볼륨의 DA 설정이 동일해야 합니다.

