---
permalink: sm-mirroring/requirements-for-using-synchronous-mirroring.html 
sidebar: sidebar 
keywords: requirements, synchronous, mirroring 
summary: 동기 미러링 기능을 사용하는 경우 다음 요구 사항을 염두에 두십시오. 
---
= 동기 미러링 사용에 대한 요구 사항
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
동기 미러링 기능을 사용하는 경우 다음 요구 사항을 염두에 두십시오.



== SANtricity 유니파이드 관리자

동기식 미러링 기능을 사용하려면 여러 스토리지 어레이를 관리해야 하므로 브라우저 기반 SANtricity Unified Manager가 설치되어 있어야 하며 데이터를 미러링할 두 스토리지 어레이가 검색되었습니다. 그런 다음 Unified Manager에서 운영 볼륨의 스토리지 어레이를 선택하고 Launch를 클릭하여 브라우저 기반 SANtricity System Manager를 엽니다.



== 지원합니다

* 두 개의 스토리지 어레이가 있어야 합니다.
* 각 스토리지 어레이에는 2개의 컨트롤러가 필요합니다.
* 운영 및 2차 볼륨의 스토리지 어레이에서 다양한 OS 버전을 실행할 수 있습니다. 지원되는 최소 버전은 7.84입니다.
* 로컬 및 원격 스토리지 배열의 암호를 알아야 합니다.
* 미러링할 운영 볼륨과 같거나 더 큰 보조 볼륨을 생성하려면 원격 스토리지 시스템에 사용 가능한 용량이 충분해야 합니다.
* 로컬 및 원격 스토리지 시스템은 Fibre Channel Fabric을 통해 접속되어야 합니다.




== 지원되는 하드웨어 구성 및 연결

* 동기식 미러링은 이중 컨트롤러 하드웨어 구성에서만 지원됩니다.
* 동기식 미러링을 위한 통신은 FC(Fibre Channel) 호스트 포트가 있는 컨트롤러에서만 지원됩니다.
* 동기 미러링은 로컬 스토리지 배열과 원격 스토리지 배열의 각 컨트롤러에서 가장 높은 번호의 호스트 포트를 사용합니다. 컨트롤러 HBA(호스트 버스 어댑터) 호스트 포트 4는 일반적으로 미러 데이터 전송용으로 예약되어 있습니다.




== 미러링 볼륨 후보

* 동기식 미러링 쌍의 운영 볼륨과 2차 볼륨에서는 RAID 레벨, 캐싱 매개 변수, 세그먼트 크기가 다를 수 있습니다.
* 동기식 미러링 쌍의 운영 볼륨과 2차 볼륨은 표준 볼륨이어야 합니다. 씬 볼륨 또는 스냅샷 볼륨일 수 없습니다.
* 2차 볼륨의 크기는 운영 볼륨만큼 크지 않아야 합니다.
* 운영 볼륨에만 연결된 스냅샷이 있거나 볼륨 복제 작업의 소스 또는 타겟 볼륨일 수 있습니다.
* 볼륨은 하나의 미러 관계에만 참여할 수 있습니다.




== 예약된 용량입니다

* 컨트롤러 재설정 및 기타 임시 중단으로부터 복구하기 위해 쓰기 정보를 로깅하기 위해 운영 볼륨과 보조 볼륨에 예약된 용량이 필요합니다.
* 예약된 용량 볼륨은 동기식 미러링이 활성화될 때 자동으로 생성됩니다. 미러링된 쌍의 운영 볼륨과 2차 볼륨 모두에 예약된 용량이 필요하므로 동기 미러 관계에 참여하는 두 스토리지 시스템에서 사용 가능한 용량이 충분한지 확인해야 합니다.




== 드라이브 보안 기능

* 보안 가능 드라이브를 사용하는 경우 기본 볼륨 및 보조 볼륨에 호환되는 보안 설정이 있어야 합니다. 이 제한은 적용되지 않으므로 직접 확인해야 합니다.
* 보안 가능 드라이브를 사용하는 경우 기본 볼륨과 보조 볼륨은 동일한 드라이브 유형을 사용해야 합니다. 이 제한은 적용되지 않으므로 직접 확인해야 합니다.
+
** 기본 볼륨에서 FDE(전체 디스크 암호화) 드라이브를 사용하는 경우 보조 볼륨에서 FDE 드라이브를 사용해야 합니다.
** 운영 볼륨이 FIPS(Federal Information Processing Standards 140-2) 검증 드라이브를 사용하는 경우 2차 볼륨은 FIPS 140-2 검증을 거친 드라이브를 사용해야 합니다.


* DA(Data Assurance)를 사용하는 경우 운영 볼륨과 보조 볼륨의 DA 설정이 동일해야 합니다.

