---
permalink: sm-interface/whats-new-in-sam.html 
sidebar: sidebar 
keywords: new, santricity, system manager 
summary: System Manager에는 다음과 같은 새로운 기능이 포함되어 있습니다. 
---
= SANtricity 시스템 관리자의 새로운 기능
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
System Manager에는 다음과 같은 새로운 기능이 포함되어 있습니다.



== 버전 11.53의 새로운 기능

이 버전에는 사소한 개선 사항 및 수정 사항만 포함되어 있습니다.



== 버전 11.52의 새로운 기능

|===
| 새로운 기능 | 설명 


 a| 
NVMe over FC 호스트 인터페이스
 a| 
이제 NVMe over RoCE 및 NVMe over InfiniBand에 대한 기존 지원 외에도 EF570 또는 E5700 컨트롤러 모델에 대해 NVMe over Fibre Channel 호스트 연결을 주문할 수 있습니다. System Manager에는 "NVMe over Fibre Channel details" 아래의 Settings[System] 메뉴에서 이 새로운 연결 유형에 대한 통계가 포함되어 있습니다.

|===


== 버전 11.51의 새로운 기능

이 버전에는 사소한 개선 사항 및 수정 사항만 포함되어 있습니다.



== 버전 11.50의 새로운 기능

|===
| 새로운 기능 | 설명 


 a| 
NVMe over RoCE 인터페이스
 a| 
이제 EF570 또는 E5700 DE Series 컨트롤러에 대해 NVMe over RoCE 호스트 연결을 주문할 수 있습니다. System Manager에는 호스트에 대한 네트워크 연결을 구성하는 새로운 기능이 포함되어 있습니다(하드웨어 페이지 또는 메뉴: 설정 [시스템] 에서 사용 가능, 스토리지 어레이에 대한 NVMe over RoCE 연결에 대한 데이터 보기 기능(메뉴: 지원 [지원 센터] 또는 메뉴: 설정 [시스템] 에서 사용 가능).



 a| 
볼륨 그룹에 대한 수동 드라이브 선택
 a| 
볼륨 그룹을 생성할 때 편리한 자동 선택 기능 외에도 개별 드라이브를 선택할 수 있는 새로운 옵션이 제공됩니다. 일반적으로 자동 드라이브 선택이 권장되지만 특별한 드라이브 위치 요구 사항이 있는 환경에서는 개별 드라이브 선택 옵션을 사용할 수 있습니다.



 a| 
SANtricity 유니파이드 관리자
 a| 
Unified Manager는 E2800 시리즈 컨트롤러 및 E5700 시리즈 컨트롤러를 검색하고 관리하는 별도의 브라우저 기반 애플리케이션입니다. 이 새로운 애플리케이션은 System Manager의 새로운 기능이 아니지만 검색된 스토리지 어레이에 대해 System Manager를 실행할 수 있는 새로운 브라우저 기반 엔터프라이즈 프레임워크를 제공합니다. 새 Unified Manager는 지원 소프트웨어 다운로드 영역에서 다운로드할 수 있습니다.

|===