---
permalink: sm-hardware/configure-nvme-over-infiniband-ports-hardware.html 
sidebar: sidebar 
keywords: configure, nvme, infiniband, ports 
summary: 컨트롤러에 InfiniBand 연결을 통한 NVMe가 포함된 경우 하드웨어 페이지 또는 시스템 페이지에서 NVMe 포트 설정을 구성할 수 있습니다. 
---
= InfiniBand 포트를 통해 NVMe를 구성합니다
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
컨트롤러에 InfiniBand 연결을 통한 NVMe가 포함된 경우 하드웨어 페이지 또는 시스템 페이지에서 NVMe 포트 설정을 구성할 수 있습니다.

.시작하기 전에
* 컨트롤러에서 NVMe over InfiniBand 호스트 포트를 포함해야 합니다. 그렇지 않으면 System Manager에서 NVMe over InfiniBand 설정을 사용할 수 없습니다.
* 호스트 연결의 IP 주소를 알아야 합니다.


하드웨어 페이지 또는 설정 [시스템] 메뉴에서 NVMe over InfiniBand 구성에 액세스할 수 있습니다. 이 작업에서는 * 하드웨어 * 페이지에서 포트를 구성하는 방법에 대해 설명합니다.

[NOTE]
====
NVMe over InfiniBand 설정 및 기능은 스토리지 어레이 컨트롤러에 NVMe over InfiniBand 포트가 포함된 경우에만 표시됩니다.

====
.단계
. 하드웨어 * 를 선택합니다.
. 그래픽에 드라이브가 표시되면 * 쉘프 뒷면 표시 * 를 클릭합니다.
+
그래픽이 변경되어 드라이브 대신 컨트롤러가 표시됩니다.

. 구성할 NVMe over InfiniBand 포트가 있는 컨트롤러를 클릭합니다.
+
컨트롤러의 상황에 맞는 메뉴가 나타납니다.

. Configure NVMe over InfiniBand ports * 를 선택합니다.
+
InfiniBand 포트를 통한 NVMe 구성 * 대화 상자가 열립니다.

. 드롭다운 목록에서 구성할 HIC 포트를 선택한 다음 호스트의 IP 주소를 입력합니다.
. 구성 * 을 클릭합니다.
. 구성을 완료한 다음 * Yes * 를 클릭하여 NVMe over InfiniBand 포트를 재설정합니다.

