---
permalink: sm-settings/certificate-terminology.html 
sidebar: sidebar 
keywords: certificate, terminology 
summary: 인증서 조건이 스토리지 어레이에 적용되는 방식에 대해 알아보십시오. 
---
= 인증서 용어
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
인증서 조건이 스토리지 어레이에 적용되는 방식에 대해 알아보십시오.

|===
| 기간 | 설명 


 a| 
CA
 a| 
CA(인증 기관)는 인터넷 보안을 위해 디지털 인증서라는 전자 문서를 발급하는 신뢰할 수 있는 엔터티입니다. 이러한 인증서는 클라이언트와 서버 간의 보안 연결을 허용하는 웹사이트 소유자를 식별합니다.



 a| 
CSR
 a| 
CSR(인증서 서명 요청)은 신청자가 CA(인증 기관)로 보내는 메시지입니다. CSR은 CA가 인증서를 발급하는 데 필요한 정보를 확인합니다.



 a| 
인증서
 a| 
인증서는 보안 목적으로 사이트의 소유자를 식별하므로 공격자가 사이트를 가장할 수 없습니다. 인증서에는 사이트 소유자에 대한 정보와 이 정보를 인증(서명)한 신뢰할 수 있는 엔터티의 ID가 포함되어 있습니다.



 a| 
클라이언트 인증서
 a| 
보안 키 관리를 위해 클라이언트 인증서는 스토리지 배열의 컨트롤러를 검증하므로 키 관리 서버가 해당 IP 주소를 신뢰할 수 있습니다.



 a| 
키 관리 서버 인증서입니다
 a| 
보안 키 관리를 위해 키 관리 서버 인증서는 서버의 유효성을 검사하므로 스토리지 배열이 해당 IP 주소를 신뢰할 수 있습니다.



 a| 
관리 인증서
 a| 
관리 인증서는 CA(인증 기관)에 의해 승인되며 웹 응용 프로그램에 대한 보안 액세스를 허용합니다. "서명된 인증서"라고도 합니다.



 a| 
OCSP 서버
 a| 
OCSP(Online Certificate Status Protocol) 서버는 CA(인증 기관)가 예약된 만료 날짜 이전에 인증서를 취소할지 여부를 확인한 다음 인증서가 해지되면 사용자가 서버에 액세스하지 못하도록 차단합니다.



 a| 
자체 서명된 인증서
 a| 
자체 서명된 인증서가 컨트롤러에 미리 로드됩니다. 사이트 연결이 자체 서명된 경우 웹 응용 프로그램으로 진행하기 전에 경고 메시지가 열립니다.



 a| 
신뢰할 수 있는 인증서입니다
 a| 
CA(인증 기관)의 신뢰할 수 있는 인증서는 인증서 계층 구조의 맨 위에 있는 알려진 인증서입니다. "루트 인증서"라고도 합니다.

|===