---
permalink: sm-settings/step-1-complete-a-csr.html 
sidebar: sidebar 
keywords: complete, ca certificate, signing, request, csr, controllers 
summary: '스토리지 배열 컨트롤러의 CA(인증 기관) 인증서를 받으려면 먼저 저장소 배열의 각 컨트롤러에 대해 CSR(인증서 서명 요청) 파일을 생성해야 합니다.' 
---
= 컨트롤러에 대한 CA 인증서 서명 요청(CSR)을 완료합니다
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
스토리지 배열 컨트롤러의 CA(인증 기관) 인증서를 받으려면 먼저 저장소 배열의 각 컨트롤러에 대해 CSR(인증서 서명 요청) 파일을 생성해야 합니다.

.시작하기 전에
* 보안 관리자 권한이 포함된 사용자 프로필로 로그인해야 합니다. 그렇지 않으면 인증서 기능이 나타나지 않습니다.


이 작업에서는 컨트롤러에 대한 서명된 관리 인증서를 받기 위해 CA로 보내는 .csr 파일(인증서 서명 요청)을 생성하는 방법에 대해 설명합니다. 조직에 대한 정보와 컨트롤러의 IP 주소 또는 DNS 이름을 제공해야 합니다. 이 작업 중에 스토리지 어레이에 컨트롤러가 하나만 있고 컨트롤러가 두 개인 경우 .csr 파일이 두 개 있는 경우 .csr 파일이 하나 생성됩니다.

.단계
. 설정 [인증서] 메뉴를 선택합니다.
. 어레이 관리 * 탭에서 * CSR 완료 * 를 선택합니다.
+
[NOTE]
====
두 번째 컨트롤러에 대해 자체 서명된 인증서를 수락하라는 대화 상자가 표시되면 * 자체 서명된 인증서 수락 * 을 클릭하여 계속 진행합니다.

====
. 다음 정보를 입력하고 * 다음 * 을 클릭합니다.
+
** * 조직 * -- 회사 또는 조직의 전체 법적 이름. Inc. 또는 Corp.와 같은 접미사를 포함합니다
** * 조직 단위(선택 사항) * -- 인증서를 처리하는 조직의 사업부입니다.
** * 시/군/구 * -- 스토리지 배열 또는 비즈니스가 위치한 시/군/구.
** * 주/지역(선택 사항) * -- 스토리지 배열 또는 비즈니스가 위치한 주 또는 지역입니다.
** * 국가 ISO 코드 * -- 미국 등 해당 국가의 2자리 ISO(International Organization for Standardization) 코드입니다.


+
[CAUTION]
====
일부 필드는 컨트롤러의 IP 주소와 같은 적절한 정보로 미리 채워질 수 있습니다. 값이 올바르지 않다고 확신하지 않는 한 미리 채워진 값을 변경하지 마십시오. 예를 들어 CSR을 아직 완료하지 않은 경우 컨트롤러 IP 주소는 ""localhost""로 설정됩니다. 이 경우 "localhost"를 컨트롤러의 DNS 이름 또는 IP 주소로 변경해야 합니다.

====
. 스토리지 어레이에서 컨트롤러 A에 대한 다음 정보를 확인하거나 입력합니다.
+
** * Controller a common name * -- 컨트롤러 A의 IP 주소 또는 DNS 이름이 기본적으로 표시됩니다. 이 주소가 올바른지 확인합니다. 입력한 주소와 정확하게 일치해야 브라우저에서 System Manager에 액세스할 수 있습니다.
** * 컨트롤러 대체 IP 주소 * -- 공통 이름이 IP 주소인 경우 컨트롤러 A에 대한 추가 IP 주소 또는 별칭을 선택적으로 입력할 수 있습니다 여러 항목의 경우 쉼표로 구분된 형식을 사용합니다.
** * 컨트롤러 A 대체 DNS 이름 * -- 공통 이름이 DNS 이름이면 컨트롤러 A의 추가 DNS 이름을 입력합니다 여러 항목의 경우 쉼표로 구분된 형식을 사용합니다. 대체 DNS 이름이 없지만 첫 번째 필드에 DNS 이름을 입력한 경우 여기에 해당 이름을 복사합니다. 스토리지 배열에 컨트롤러가 하나만 있는 경우 * Finish * (마침 *) 버튼을 사용할 수 있습니다. 스토리지 배열에 컨트롤러가 두 개 있는 경우 * Next * (다음 *) 버튼을 사용할 수 있습니다.


+
[NOTE]
====
CSR 요청을 처음 생성할 때 * 이 단계 건너뛰기 * 링크를 클릭하지 마십시오. 이 링크는 오류 복구 상황에서 제공됩니다. 드문 경우지만 한 컨트롤러에서 CSR 요청이 실패할 수 있지만 다른 컨트롤러에서는 그렇지 않습니다. 이 링크를 사용하면 컨트롤러 A에서 CSR 요청을 생성하는 단계를 건너뛸 수 있습니다(이미 정의된 경우). 컨트롤러 B에서 CSR 요청을 다시 생성하기 위한 다음 단계를 계속 진행할 수 있습니다

====
. 하나의 컨트롤러만 있는 경우 * 마침 * 을 클릭합니다. 두 개의 컨트롤러가 있는 경우 * 다음 * 을 클릭하여 컨트롤러 B에 대한 정보(위와 동일)를 입력한 다음 * 마침 * 을 클릭합니다.
+
단일 컨트롤러의 경우 .csr 파일 하나가 로컬 시스템에 다운로드됩니다. 이중 컨트롤러의 경우 .csr 파일 두 개가 다운로드됩니다. 다운로드의 폴더 위치는 브라우저에 따라 다릅니다.

. CA로 .csr 파일을 보냅니다.


디지털 인증서를 받으면 CA가 보낸 적절한 인증서 파일을 가져옵니다.
